//! OS-backed host integration for the Bop programming language.
//!
//! [`StandardHost`] implements [`bop::BopHost`] for command-line, desktop,
//! and server applications that intentionally want ordinary process
//! capabilities. It:
//!
//! - writes Bop's `print(...)` output to stdout;
//! - exposes `readline`, UTF-8 file reads and writes, environment lookup, and
//!   Unix time as host functions;
//! - resolves dot-separated module names beneath a guarded filesystem root;
//! - resolves Bop's bundled `std.*` modules first when the default `bop-std`
//!   feature is enabled.
//!
//! # Running a program
//!
//! ```
//! use bop::BopLimits;
//! use bop_sys::StandardHost;
//!
//! let mut host = StandardHost::new();
//! bop::run(
//!     r#"use std.math.{PI}
//! print("pi = {PI}")"#,
//!     &mut host,
//!     &BopLimits::standard(),
//! ).unwrap();
//! ```
//!
//! The same host works with `bop_vm::run` and with Rust generated by
//! `bop-compile`.
//!
//! # Filesystem modules
//!
//! [`StandardHost::with_module_root`] maps `use app.config` to
//! `<root>/app/config.bop`. Module names are validated before joining, so
//! separators, empty segments, and traversal components cannot escape the
//! configured root. [`resolve_module_from_root`] exposes that filesystem-only
//! behavior for build tools and AOT module resolvers.
//!
//! # Trust boundary
//!
//! This crate is deliberately not a sandbox: scripts can call the enabled
//! filesystem, environment, stdin, and clock functions. Applications running
//! untrusted code should implement a narrow [`bop::BopHost`] instead and only
//! expose approved capabilities.
//!
//! See the [embedding guide](https://bop-lang.com/docs/embedding/) for the
//! complete host-function table and custom-host examples.

mod args;
mod env;
mod error;
mod fs;
mod host;
mod stdio;
mod time;

pub use host::{resolve_module_from_root, StandardHost, StdHost};
